name: dprint

on:
  workflow_call:
    inputs:
      dprint-version:
        description: dprint version to use
        type: string
        required: true
      config-path:
        description: Path to dprint config file
        type: string
        default: ''

jobs:
  dprint:
    runs-on: ubuntu-latest
    steps:
      - uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3
        with:
          dprint-version: ${{ inputs.dprint-version }}
          config-path: ${{ inputs.config-path }}
