name: Test setup-nix

on:
  pull_request:
    paths:
      - setup-nix/**
      - .github/workflows/test-setup-nix.yml
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./setup-nix

      - run: nix --version
